### ISSUE TITLE
Please support pluggable security controls standards

### ISSUE THREAD

**Issue by javabeanz** [blabla1337/skf-flask#102]
Currrently, security controls fomr the OWASP ASVS standard are used in SKF, but the Dutch government has its own list of security controls :https://www.cip-overheid.nl/wp-content/uploads/2015/05/Grip-on-SSD-Security-Requirements-v2.0.pdf (SSD-1 t/m SSD-31). NCSC has its own (https://www.ncsc.nl/actueel/whitepapers/ict-beveiligingsrichtlijnen-voor-webapplicaties.html) and NIST has its list and ISO27002 too.
If you make the security controls/requirements pluggable, other standards than OWASP ASVS can be supported as well. What would it take to make this possible ?

**Comment by RiieCco** [comment]
Hey,

You can easily change the checklist by changing the markdown files in the
custom checklist section. In the next planned release of skf the whole
checklist function wil be
Dynamic an interchangeable

For the current markdown files you van check the checklist folder in te
project to Find the markdown files that make up the checklist and the
skf.readme.io has an explanation how the files are structured.

If u have any feedback or desired new features please let us know so we can
take it into consideration with the new skf release.

With kind regards,
Skf team!

Op maandag 14 november 2016 heeft javabeanz <notifications@github.com> het
volgende geschreven:

**Comment by jmanico** [comment]
Hey there. The ASVS requirements can be used for many purposes. What
would need to change to make them more plugged per your perspective? I
think they are pretty pluggable as is....

Aloha, Jim

**Comment by javabeanz** [comment]
Hi Jim, Ricardo,

Thanks for your replies. I will look into the code to see where I can
modify the code to fit the other standards.

The OWASP ASVS is now in status ASSESS on the Thoughtworks Technology Radar
: https://www.thoughtworks.com/radar/techniques Would they know SKF yet ?

cheers,

javabeanz.

**Comment by blabla1337** [comment]
With the new release of SKF we can have dynamic and custom checklist build on the fly in SKF.
No need to have this ticket open and will close it.

**Comment by javabeanz** [comment]
Glen, is this documented somewhere so i can start that custom checklist ?

**Comment by blabla1337** [comment]
Hi Javabeanz, 

Good point but not yet, we are waiting for the ASVS 4.0 to finalise so we can include it in our upcoming release. In this new upcoming release you will have also the possibility to create these custom checklist in SKF UI. We will update the https://skf.readme.io page with the new functionality and explanation on how to create the custom checklists in SKF.

If you cannot wait and already want to have a look you can clone the SKF dev branch and have a look ;)

**Comment by javabeanz** [comment]
Loogin forward to the new SKF, and hope to see some documentation for custom checklists. Dutch government security regulations for instance use BIR as reference and it would be nice to have this supported.
