### ISSUE TITLE
No natural way to run Docker image with external data volume

### ISSUE THREAD

**Issue by adedov** [blabla1337/skf-flask#105]
Hi!

Currently there is no natural way to use Docker version of SKF with database stored on external data volume. The database skf.db file comes predefined (hardcoded) so binding external db-file requires a copy of skf.db from git repo or from created container.

Alternatively one can now bind skf.db file to an empty file on a node and then do following command just after first start of a container:
`docker exec 038620eccd6d sh -c "sqlite3 skf.db < schema.sql"`

**Fix proposal**:  Use some database change management tool like alembic and run it on an container start. Allow to skip it with command line option, like docker run owasp-skf --no-initdb.

**Comment by xandfury** [comment]
Flask-migrate can be used to fix the issue. Issue #93 would addresses this.

**Comment by blabla1337** [comment]
we created how to for docker to store the database outside the container:
Example docker run to use:

docker run -v /Users/gibson/Desktop/development/skf-flask/skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite -e "ORIGIN=localhost" -e "JWT_SECRET=change_this_super_secret_random_string" -ti -p 127.0.0.1:443:443 blabla1337/skf-flask
