### ISSUE TITLE
ImportError: No module named bcrypt - fix / workaround

### ISSUE THREAD

**Issue by razvanionescu** [blabla1337/skf-flask#106]
Environment: Kali Linux, Python 2.7
I have followed these instructions in order to install skf: 
sudo apt-get install python-pip sqlite3 lib32z1-dev python-dev libxml2-dev libxslt-dev libffi-dev libssl-dev
sudo pip install https://github.com/mitsuhiko/flask/tarball/master
sudo pip install owasp-skf

When I was trying to run python skf.py, it failed due to the following error:
Traceback (most recent call last):
  File "skf.py", line 30, in <module>
    from flask_bcrypt.bcrypt import Bcrypt
ImportError: No module named bcrypt

Despite the fact that I have all the necessary modules in place (within python2.7/dist-packages).

My small fix was the following:
Inside skf.py file do the following modifications: 
1. replace: "from flask_bcrypt.bcrypt import Bcrypt" with "import flask_bcrypt"
2. replace "bcrypt = Bcrypt(app)" with "bcrypt = flask_bcrypt.Bcrypt(app)"

Maybe it is just a local workaround for myself... If this is a bug, you may include the above fix in the next release.
Thank you!

**Comment by xandfury** [comment]
I would not recommend the installation method you have used. Creating virtualenv is definitely better than installing the package along with other python packages. Changing

`from flask_bcrypt.bcrypt import Bcrypt` to `from flask.ext.bcrypt import Bcrypt` in `skf.py` would fix it for me.

**Comment by blabla1337** [comment]
fixed in new release
