### ISSUE TITLE
DOCX Function Report 

### ISSUE THREAD

**Issue by kenmasters1** [blabla1337/skf-flask#107]
If I go to Results > Functions and select "View Results", the screen says:

> Summary of all function-results, you can download a DOCX file with the current security findings.

However, there is no button to download the DOCX.

I see a "Download Report" button for _Checklist_ reports, but **not** _Functions_.

How do I get this working?

**Comment by josh-gomez72** [comment]
In the results-function-report.html change line 48 from {% if entries.projectName == Null %} to {% if entries.projectName != Null %}
I have no idea why it seems reversed but managed to get it working for me

**Comment by blabla1337** [comment]
removed it for the new version
