### ISSUE TITLE
Broken and out of date

### ISSUE THREAD

**Issue by adamnfish** [blabla1337/skf-flask#122]
This repository is pretty out of date and is broken and barely usable in its current state.

I've put a bit of effort into updating [our fork of the project](https://github.com/guardian/skf-flask). It pulls a few of the important PRs that have been long outstanding as well as a few other fixes. If this original repo does get picked up I'd recommend starting from that as a baseline for future development because most stuff is now conflicting.

If you aren't sure whether the original repo will get picked up can I recommend opening its administration up to a few more of the contributors? This remains a really useful project and I'd be sad if the broken master branch on the original repo is keeping people from taking advantage of what this app offers.

**Comment by blabla1337** [comment]
Hi Adam,

I'm sorry to hear that the current state of the project is in a bad shape. Also I'm really glad and happy that you put some or a lot of effort in it to make it usable again. Currently me and my brother are working on a new Major release of SKF and we rebuild the whole project see also the rebuild branch. We really are happy with the work you have done and I will add you to the list of editors of the main branch. Can you please merge your forked improved version to the SKF main branch?

Again we thank you very much for helping us out and the other people who are using SKF.

Greetz,
Glenn

**Comment by adamnfish** [comment]
Thanks Glenn. I'll merge the branch I've been looking after!
