### ISSUE TITLE
Write code examples Python

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#13]
Write code examples Python

**Comment by bithinalangot** [comment]
Is it specifically for any python framework?

**Comment by blabla1337** [comment]
Hi Bithinalangot,

Well the idea of the code examples is not about what framework you will use but more on the approach a developer should take when creating certain functionality and how to make it secure.

So i'm going to use python-Flask framework but that is not the focus, but the steps and methods on how to achieve secure coding is. Please see the PHP and .NET code examples so you get a feeling what i'm trying to say ^^

**Comment by bithinalangot** [comment]
Ok.

**Comment by blabla1337** [comment]
Thanks to @h33raj  we have Django and Flask code examples now! Big ty!
