### ISSUE TITLE
Add code examples -> relevant knowledge-base items in results

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#14]
The code examples are all based on the knowledge-base items. So when we have multiple languages we can add these also to the reporting functionality. You will get: Item with Description, Solution and code example.

**Comment by oxdef** [comment]
It will be great because right now code examples and KB items are not related to each other.

**Comment by blabla1337** [comment]
We will use the SKF Chatbot for correlating the KB items and code examples.
