### ISSUE TITLE
Logout button gives a 400 error

### ISSUE THREAD

**Issue by Scopestyle** [blabla1337/skf-flask#27]
Should return back to the login page. Perhaps with a notification "You are now logged out" or something similar. Is this a common error or just on my end?

**Comment by RiieCco** [comment]
Ja dat is een error die iedereen krijgt, had iets temaken met die CSRF
tokens als et goed is

**Comment by RiieCco** [comment]
Moesten we nog naar kijken maar is er helemaal bij in geschote, thnx for
the reminder ^_^

Op 1 mei 2015 18:08 schreef Riccardo Ten cate <r.tencate77@gmail.com>:

> Ja dat is een error die iedereen krijgt, had iets temaken met die CSRF
> tokens als et goed is
>
