### ISSUE TITLE
In screen processing functions, create a tagcloud for easy to assemble functions.

### ISSUE THREAD

**Issue by Scopestyle** [blabla1337/skf-flask#28]
As the name suggests, the screen where the project processing functions gets assembled could really benefit from a tag cloud where functions could easilly be clicked, and added to the list. With the addition to add new tags (functions) manually (without a popup overlay). 

This will greatly enhance the usability of this vital part of the SKF process, as a sign of what the user should be doing and as a clear timesaver for the user.

**Comment by RiieCco** [comment]
Was done, good job !!
