### ISSUE TITLE
Creating Docker container from source 

### ISSUE THREAD

**Issue by xandfury** [blabla1337/skf-flask#338]
skf-flask is updated regularly. There are chances that the container on docker hub would be behind few commits than the bleeding edge version specified by the Dockerfile

The documentation should contain notes about building docker container from source.

**Comment by xandfury** [comment]
Adding the following would suffice:

1. Make sure that you have docker installed.
2. Download the Dockerfile
`wget https://raw.githubusercontent.com/blabla1337/skf-flask/master/Docker/Dockerfile`
3. Build the container
`docker build -t owasp-skf .`
4. Run the container 
`docker run -it -p 127.0.0.1:443:5443 owasp-skf`

Would send in a PR if devs think this is okay.

**Comment by blabla1337** [comment]
We have a docker available on the Docker Hub, also you can checkout the project and go to the Docker directory and build it there with docker build -t owasp-skf .
