### ISSUE TITLE
ASVS checklists if chapter is empty show empty message 

### ISSUE THREAD

**Issue by RiieCco** [blabla1337/skf-flask#348]

**Comment by martinmarsicano** [comment]
We should show empty message (on category row) or don't show that category?

**Comment by blabla1337** [comment]
I think it would be nice to show an empty row message like for this level the category has no security controls needed. What do you think?

**Comment by blabla1337** [comment]
This is about the checklist view in skf when you click left in the menu checklist and then a specific level right?

**Comment by martinmarsicano** [comment]
Yes, and for that level (let say level) some category (eg 13) doesn't have a requirement. Ok, I'll try to put the empty row.

**Comment by martinmarsicano** [comment]
Uploaded to my fork. Coming to master in next PL.

![screen shot 2018-02-26 at 12 21 34 pm](https://user-images.githubusercontent.com/33671308/36678540-d0588616-1aef-11e8-9129-56575082c272.png)
