### ISSUE TITLE
Docker image should mount to local DB 

### ISSUE THREAD

**Issue by RiieCco** [blabla1337/skf-flask#351]

**Comment by blabla1337** [comment]
added to readme how to

docker run -v /Users/gibson/Desktop/development/skf-flask/skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite -e "ORIGIN=localhost" -e "JWT_SECRET=change_this_super_secret_random_string" -ti -p 127.0.0.1:443:443 blabla1337/skf-flask
