### ISSUE TITLE
Add anti-code examples and tests based on it

### ISSUE THREAD

**Issue by oxdef** [blabla1337/skf-flask#353]
It will be great if SKF has built-in simple training functionality like tests in http://www.gameofhacks.com. It can be done using code examples with security issues (anti-code examples :) so developers can be tested by it.

**Comment by blabla1337** [comment]
Yeah I know what you mean and I agree it would add a lot of value, we decided years ago to keep this separate but maybe we should also include it somehow. If you have good ideas or wanna contribute let us know please 👍
