### ISSUE TITLE
Forced to add irrelevant info while making a project

### ISSUE THREAD

**Issue by adamnfish** [blabla1337/skf-flask#357]
The new wizard forces developers to fill everything out ahead of time. The pre-development settings screen isn't useful, but at least that one can be ignored. Having to add a sprint when creating the project is silly. Not everyone that uses the SKF will have sprints and even if they do, this isn't the time to be adding them because the target audience for "adding sprints" and "creating a new project" are different people.

I use the SKF for its knowledge base and checklists. While I certainly don't mean to suggest that's how anyone else uses it, dropping that use case is a shame.

**Comment by RiieCco** [comment]
Hey Adam,

Thanks for al the good feedback!
May i suggest doing a conference call to discuss improvements in the
framework together?

With kind regards,
Riccardo

Op 27 jul. 2017 5:30 p.m. schreef "Adam Fisher" <notifications@github.com>:

**Comment by blabla1337** [comment]
Let us know if you want to discuss so we can incorporate the feedback for next releases.

Also you can still use the Knowledge base + checklist approach, when you are at the SKF dashboard you can select Checklists menu. From there select the level of the checklist and there you find all the checklist items. When you click on the checklist item then you get the correlated knowledge base item.
