### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by adamnfish** [blabla1337/skf-flask#358]
The project depends on the `secrets` module which is new in Python 3.6. I realise it's 2017 and everyone should be using Python 3 but sadly that just isn't the reality of the world. Is there a workaround for versions of Python before 3.6?

**Comment by blabla1337** [comment]
I think we can remove that part and create a solution so it will also work in Python 2.x

**Comment by blabla1337** [comment]
No response and to old, not going to implement this Python2 is to old to put a lot of effort for
