### ISSUE TITLE
DB incompatibility with pre-rebuild version

### ISSUE THREAD

**Issue by adamnfish** [blabla1337/skf-flask#360]
I've not got the rebuild running yet so I can't test this for sure, but it looks like the rebuild is incompatible with existing SKF databases. This means individuals or organisations that have been using the security knowledge framework have to throw away what they've done and start again.

It'd be good to investigate whether it's possible to migrate old databases.

**Comment by blabla1337** [comment]
No response and to old, not going to implement this
