### ISSUE TITLE
Add reporting functionality

### ISSUE THREAD

**Issue by simonec73** [blabla1337/skf-flask#369]
There is the need to add a reporting functionality, for the Project. It is required to provide documentation on the activities done on the project.
Possible outputs, are: PDF, DOCX, HTML. You can pick the best for you, no problem, but a report is needed.

This is related to Issue #107.

**Comment by martinmarsicano** [comment]
I think the best for this, could be implement the export functionality mentioned on issue #368 and make it compatible with OWASP Defect-Dojo project which already have a report functionality. Or we also can insert findings via Dojo API (https://github.com/aaronweaver/defectdojo_api). One advantage is that everything is written in python.
Projects page: https://www.owasp.org/index.php/OWASP_DefectDojo_Project#tab=Main
Github page: https://github.com/DefectDojo/django-DefectDojo#demo

I'm planning to implement one of both functionalities when I have some time.

<img width="1889" alt="screen shot 2018-01-30 at 8 23 42 pm" src="https://user-images.githubusercontent.com/33671308/35597074-85e0f4fa-05fb-11e8-87a6-68311943c7d9.png">

**Comment by RiieCco** [comment]
CSV export is stil there, also can pin individual items to clipboard.
