### ISSUE TITLE
Unable to complete install

### ISSUE THREAD

**Issue by stevespringett** [blabla1337/skf-flask#37]
Running Ubuntu 14.04

Ran:
sudo apt-get install python-pip sqlite3
sudo pip install https://github.com/mitsuhiko/flask/tarball/master
sudo pip install owasp-skf

installing owasp-skf fails with error:

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip_build_root/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:8:22: fatal error: pyconfig.h: No such file or directory

 #include "pyconfig.h"

                      ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SZKpc9-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /home/user/.pip/pip.log

**Comment by blabla1337** [comment]
Hi Steve,

It seems you are still missing some packages, can you try this first:
sudo apt-get install python-dev libxml2-dev libxslt-dev

Greetz,
Glenn

**Comment by RiieCco** [comment]
Hey Steve,

Thanx for the heads up!

I am goin to spawn an Ubuntu myself to see if the installer might be
incomplete.



2015-05-18 21:40 GMT+02:00 Steve Springett <notifications@github.com>:

**Comment by stevespringett** [comment]
Thanks for the quick replies.

Executing:
sudo apt-get install python-dev libxml2-dev libxslt-dev
got me a bit further, but later complained that:
/usr/bin/ld: cannot find -lz

Ran
sudo apt-get install lib32z1-dev
and the install was able to complete

However, /opt/owasp-skf doesn't exist, so I'm not sure where the installer put it.

**Comment by RiieCco** [comment]
Hey Steve,

The installer put's it somewhere near:

*/usr/local/lib/python2.7/site-packages/skf*

could differ a bit from your device but it puts it in the python folder

2015-05-18 21:58 GMT+02:00 Steve Springett <notifications@github.com>:

**Comment by stevespringett** [comment]
Found it in dist-packages.
Ran:
sudo python skf.py

I see the generated password and the following:
Running on https://127.0.0.1:5443/

Does it only bind to the loopback? It doesn't respond when connecting via it's external IP address and the machine is headless. 

Running:
wget --no-check-certificate  https://127.0.0.1:5443
works and I'm able to get index.html

**Comment by blabla1337** [comment]
Yeah from a security point of view we did not want to do this as a default setting.
You can change in the skf.py the 127.0.0.1 to 0.0.0.0

Start skf.py again and now it's external facing.

Also i would suggest to not run it as root ^^

**Comment by stevespringett** [comment]
:) Thank you. 

Had to sudo chown -R user:user skf so that I did not have to run it as root. And changed the ip to 0.0.0.0 and I'm able to login.

**Comment by blabla1337** [comment]
Check ^^ 
Thanks for the feedback, we improved the Ubuntu installation part
