### ISSUE TITLE
User management 

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#38]
Add support for multiple users 
user management model
LDAP integration as part of this enhancement.

**Comment by stevespringett** [comment]
I'd also like to see LDAP integration as part of this enhancement.

**Comment by blabla1337** [comment]
Yeah totally agree, will add it to the item.

**Comment by RiieCco** [comment]
Not yet with LDAP but first draft will be available soon!

**Comment by shayvilk** [comment]
i can't find any SSO or LDAP integration documented, was this added?
