### ISSUE TITLE
Unable to get Requirements

### ISSUE THREAD

**Issue by ksaylor11** [blabla1337/skf-flask#39]
On Debian 8, I've been unable to pull in the BeautifulSoup package when I go to install owasp-skf as per instruction.

`Collecting BeautifulSoup (from -r requirements.txt (line 5))
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-d48vmbx1/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d48vmbx1/BeautifulSoup`

**Comment by blabla1337** [comment]
Hi ksaylor11,

That error i've seen before when i was trying it to run on Python 3.x
What version of python are you using?

We do support and testing for 2.6 and 2.7 at the moment

**Comment by ksaylor11** [comment]
I was able to get it to work by cloning the repo and following those instructions using python2. Sorry for the bother!
