### ISSUE TITLE
Docker make options for localhost or IP based

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#421]
It would be a nice feature if we had the ability to define the external URL as an environment variable when running the docker container (and have the API work as expected).

**Comment by NimaSaed** [comment]
Hi blabla, any update on [this](https://skf.readme.io/discuss/5a4cde158609fd0028531fc9). I need same thing and I have same problem.

**Comment by blabla1337** [comment]
Hi Guys,

I have updated the Docker config, now it should work when you set the ORIGIN variable.
Please try it again :)
