### ISSUE TITLE
Correct the order of the checklist on Sprint Summary

### ISSUE THREAD

**Issue by martinmarsicano** [blabla1337/skf-flask#424]
There is a bug on Sprint Summary. The checklists are appearing ordered by "character" (1.0, 10.0, 19.1, 2.17, 2.2), instead of by number 1.0, 2.0, 2.1, 2.2 .. 10.0.

<img width="587" alt="screen shot 2018-01-26 at 2 33 54 pm" src="https://user-images.githubusercontent.com/33671308/35452749-6cc2168c-02a6-11e8-8dc5-02b9b3338869.png">

**Comment by blabla1337** [comment]
Big thanks for your fix!
