### ISSUE TITLE
Docker app does not work with custom port

### ISSUE THREAD

**Issue by adedov** [blabla1337/skf-flask#445]
First-run functionality doesn't work when docker container bound to port other than 443. Looks like API calls proceed to a domain, ignoring port number.

Command:
> docker run -e "ORIGIN=localhost:8443" -e "JWT_SECRET=secret" -ti -p 127.0.0.1:8443:443 blabla1337/skf-flask

As a result first-login functionality fails with error. See screenshot
<img width="1552" alt="screen shot 2018-04-18 at 17 15 38" src="https://user-images.githubusercontent.com/3448606/38940552-10ed858a-4333-11e8-8d77-57980b1b2d8f.png">

**Comment by blabla1337** [comment]
Indeed that is correct because the https:// is hardcoded in the Angular environment file and if you want to use a different port you need to change it there then: 

https://github.com/blabla1337/skf-flask/blob/master/Angular/src/environments/environment.prod.ts
