### ISSUE TITLE
wording for OWASP Top 10 A5 - director listing

### ISSUE THREAD

**Issue by mavensecurity** [blabla1337/skf-flask#45]
The question reads, "Directory listing is enabled on your server?" but if you mark your answer "Yes" then is shades it green as if that is a good response.  Isn't "No" the passing response, since you do not generally want directory listings enabled?

**Comment by RiieCco** [comment]
Thanx for the heads up, indeed the question was formulated wrong. Will
change that right away! :)




2015-06-01 2:30 GMT+02:00 mavensecurity <notifications@github.com>:

**Comment by RiieCco** [comment]
Question was formulated differently, so also fixed.
Will update pip package tonight :)
