### ISSUE TITLE
Connection to $bugtrackingsystem

### ISSUE THREAD

**Issue by stitch** [blabla1337/skf-flask#455]
During my security awareness sessions for developers, i demonstrate ASVS in combination with SKF. While SKF is neat, most developers tell me "oh, yet another $system" and ask for "how can i integrate with my $bugtrackingsystem".

Would it be possible to have SKF do the selection, and export this to $format (or easy copy paste) and have an altered $format-file as an input?

Is there a sensible answer to give them to help them getting started?

Should they for example try to use the API? https://github.com/blabla1337/skf-flask/tree/master/skf/api

**Comment by blabla1337** [comment]
They can use the SKF export function that already exits for example Defect-Dojo
Or create there own adaptor for their favourite  bugtracking tool see this file for an example:
https://github.com/blabla1337/skf-flask/blob/master/skf/api/sprints/business.py line 154

Yeah you can also use only the API and create your own GUI on top but I would suggest the previous options first as it will be way less work :)
