### ISSUE TITLE
Search on readme doesn't work

### ISSUE THREAD

**Issue by stitch** [blabla1337/skf-flask#456]
Using any search term on the https://skf.readme.io/ site doesn't deliver results. This makes it hard to discover features and hints about implementation.

Latest chrome, no exceptions in the developer console.

**Comment by blabla1337** [comment]
Its a third party application, will have a look what we can do.
Maybe an idea to host it in Github-> Wiki instead?

**Comment by blabla1337** [comment]
Hmm the search is indeed not working well on this platform also it's not in our control so we cannot do anything about it...
