### ISSUE TITLE
2nd Language

### ISSUE THREAD

**Issue by lylylylylylylylyly** [blabla1337/skf-flask#467]
Hi
I would like to use a second language, is there a possibility to create?
if anyone creates a button and a function to change, plus new columns in the database, I can help in translation and insert them in the database.

**Comment by blabla1337** [comment]
Hi,

For the moment not yet but this is something we want to add in the near future.
What I would recommend is to already start with the translation of the Knowledge Base items?

You can then already use them in your local instance of SKF. When we have the 2nd language feature released we then can import your work instantly and make it work :)

**Comment by blabla1337** [comment]
Duplicate ticket will close this one, for tracking the multi language see this issue:
https://github.com/blabla1337/skf-flask/issues/471
