### ISSUE TITLE
Make the SKF multi language

### ISSUE THREAD

**Issue by RiieCco** [blabla1337/skf-flask#471]
Allocate project funding to hire translators for the SKF to translate knowledgebase items, code examples and the framework itself.

**Comment by Tikam02** [comment]
### @RiieCco  We Can Use Angular Internationalization (i18n) to Make the SKF multi lingual. https://angular.io/guide/i18n

**Comment by RiieCco** [comment]
no volunteers for translating in 3 years time, so we will close it now
