### ISSUE TITLE
Docker build has no versioning

### ISSUE THREAD

**Issue by dpnl87** [blabla1337/skf-flask#486]
The latest Docker build is failing, so I'd like to pull the previous build.
This is not possible as there is only a build for the latest tag.

**Comment by blabla1337** [comment]
yes indeed, we should have a stable and a latest one.
Any suggestion how to do this easy?

**Comment by blabla1337** [comment]
Now we have on Dockerhub 3 versions, Stable, Latest and Dev
We also will version the Stable one in the future for all releases we will do
