### ISSUE TITLE
Question: Which version of ASVS is running in the latest SKF project

### ISSUE THREAD

**Issue by RithinMithra** [blabla1337/skf-flask#488]
Question:
Which version of ASVS (2.x,3.x) is running in the latest SKF project?

Can we configure SKF to use latest version of ASVS ?

**Comment by blabla1337** [comment]
We are now having version 3.x in SKF and we are busy with a new Major release of SKF that will include the new ASVS 4.x and many more cool updates and features. We are planning and aiming to release it end of this month.

**Comment by RithinMithra** [comment]
Thank you for quick response
