### ISSUE TITLE
Actual commentator details not shown in Audit logs

### ISSUE THREAD

**Issue by ravi-mrk** [blabla1337/skf-flask#504]
Commentator is hardcoded to Admin. When a Developer or a Security Specialist comments on an issue, only Admin is shown on the cards in Audit log. Find below:
1. Developer comments
<img width="1280" alt="Screenshot 2019-03-23 at 21 25 55" src="https://user-images.githubusercontent.com/13218652/54872996-561abe00-4dc5-11e9-9fc3-3b92e58058d0.png">

2. Admin user comments(This user is a Security expert in this case)
<img width="1280" alt="Screenshot 2019-03-23 at 21 27 29" src="https://user-images.githubusercontent.com/13218652/54873011-75195000-4dc5-11e9-8459-57f6465e4170.png">

3. Dev user checks the audit trail and the commentator is shown as Admin only.
<img width="1277" alt="Screenshot 2019-03-23 at 21 28 49" src="https://user-images.githubusercontent.com/13218652/54873025-aeea5680-4dc5-11e9-892c-992eaba22ea1.png">

**Comment by blabla1337** [comment]
@ravi-mrk 

We have removed this functionality from the latest version of SKF as our feedback and experience have learned us that most people export the findings to their own ticketing system and do the follow up there. Will close this issue but thanks for reporting it to us.

Kind regards,
Glenn
