### ISSUE TITLE
Volume mapping database when running in Docker

### ISSUE THREAD

**Issue by jmezach** [blabla1337/skf-flask#527]
The documentation for running in Docker states that you can externalise the database by using a volume so that it can survive restarts. However, the documentation suggests that you should put the db.sqlite file on the volume. But where do I get this file from? And shouldn't that file be generated when starting the Docker container for the first time, and not be rewritten if it is started again and the file already exists? This isn't a very good user experience for new users.

**Comment by blabla1337** [comment]
Hi @jmezach 

We have now made in the settings.py the database connection string an ENV variable. So you can easily overwrite it by setting this env variable SKF_DB_URL and point it to your external database.

The old way of mounting the db file locally is also still an option. You need to download the db file and  use it when starting the docker using the command in the how to page.

Kind regards,
Glenn
