### ISSUE TITLE
Labs - indicator: Role type

### ISSUE THREAD

**Issue by SoBart-ISO** [blabla1337/skf-flask#543]
The current labs do already have a level of maturity indicator. I would be a very nice addition if a second indicator can be added, showing the role it's applicable for. E.g. Development (=Front and Back), DevOps/Infra, Architect, Project vs Ops.

**Comment by amsharma91** [comment]
This sounds like a good idea, we could add tags on each of the labs, then allow people to filter by these tags. The only issue is not all labs could be easily grouped into a single role.

**Comment by SoBart-ISO** [comment]
Roles my be Tags, where multiple tags are possible to be added to the list.

**Comment by blabla1337** [comment]
Done by implementing the new Training feature in SKF, see SOO branch or the demo of SKF online :)
