### ISSUE TITLE
missing file CloudFormation template

### ISSUE THREAD

**Issue by scrissti** [blabla1337/skf-flask#544]
Referenced file on the cloudformation documentation page is missing https://github.com/blabla1337/skf-flask/blob/master/installations/cloudformation/owasp-security-knowledge-framework.template.yaml

**Comment by blabla1337** [comment]
Hi @scrissti yes we used to have one that worked but because of many changes this template was out of date. Do you have any experience in it and can help us build a new one?

Kind regards,
Glenn

**Comment by slewt** [comment]
Hi @scrissti, If you really needed that file for a starting point and never found it, you can find the last file in tag 1.0 as a starting point: https://github.com/blabla1337/skf-flask/blob/1.0/cloudformation/owasp-security-knowledge-framework.template.yaml

@blabla1337, 
I'd be tempted to just delete the folder for Cloud Template, Not sure it would be worth supporting. I know if I were going to support something like that, I'd want to use something like EKS and reuse the existing Docker image and not keep a separate build config from scratch up to date. For that type of work, the existing Docker image would need some modifications I'm assuming at least:

1. some paths would need changing from localhost -> relative paths 
    - based on CORS errors referencing localhost I'm seeing when trying to use the existing Docker image on an AWS EC2 instance with ORIGIN set to either the IP address or the DNS name of the instance
2. a new method for creating the first login user -  probably by the existence of environment variables
