### ISSUE TITLE
Demo page is down

### ISSUE THREAD

**Issue by bkimminich** [blabla1337/skf-flask#546]
https://demo.securityknowledgeframework.org gave
![image](https://user-images.githubusercontent.com/3531020/68090467-5f4c2d00-fe74-11e9-8ff3-f987fdda14c5.png)
(checked on 3rd November 2019)

**Comment by blabla1337** [comment]
Hi @bkimminich 

Thank you for sharing, yes I was aware and trying to troubleshoot with our VPS to see why this happened. It seemed there was a problem with Out of memory suddenly and we where not able to restart Angular anymore... 

In the end I couldn't get it solved so I moved to a better VPS and now its working again :)
