### ISSUE TITLE
external database

### ISSUE THREAD

**Issue by scrissti** [blabla1337/skf-flask#552]
Hi,
I've install the app in a docker and trying to use it with an external database.
I noticed in the skf-flask/skf/settings.py:L21  that if I create en env variable called "SKF_DB_URL" it should override the default sqllite db.
So i created a docker env variable with a new DB url but seems it ignores it. Any idea why?

**Comment by blabla1337** [comment]
Hi,

Hmm if I set the env variable locally I see it does get picked up correctly:
export SKF_DB_URL=mysql://test:the_password@localhost/bla

After starting the API and trying to retrieve the /api/kb/items I can see it uses my other DB URL?
Can you maybe tell me a bit more about your setup? You followed the local Docker setup?

Also it would be easier if you can drop into the SKF channel so we can have a chat and I can troubleshoot you.

https://gitter.im/Security-Knowledge-Framework/Lobby

Kind regards,
Glenn

**Comment by northdpole** [comment]
@blabla1337 , the SKF_DB_URL env variable only works with 

the skf-flask:latest container  has been last updated 2 months ago.
you need to push a new version of skf-flask or better create a new release of skf based on the latest changes and push skf-flask:2.02 or something ;-)
