### ISSUE TITLE
Enhancing the UI - Overlapping of Navbar

### ISSUE THREAD

**Issue by AkashM398** [blabla1337/skf-flask#554]
The Navbar of https://www.securityknowledgeframework.org website is being overlaped on the chat section, which makes me to scroll down to close the chat section.The below image shows how the UI looks like and what need to be changed. 
So I would like to work on this issue.
![UI](https://user-images.githubusercontent.com/38563661/69496495-c5b6ef00-0ef8-11ea-89ed-54dc119ef93f.jpg)

**Comment by blabla1337** [comment]
Hi @AkashM398 

Yeah you can have a look we would appreciate it. The source of that site can be found here:
https://github.com/blabla1337/skf-www

But the chat window is a default Gitter HTML snippet so I don't know how much you are able to tweak it.

Kind regards,
Glenn

**Comment by AkashM398** [comment]
Thank you @blabla1337 I'll start to work on this issue.

**Comment by AkashM398** [comment]
Issue fixed and closing #554
