### ISSUE TITLE
protocol issue 

### ISSUE THREAD

**Issue by ferrandpaul** [blabla1337/skf-flask#556]
hello,

I'm deploying the latest version of the skf flask, but i'm getting the following error :

Getting Private key
+ rm /skf-flask/server.csr
+ CERT=/skf-flask/server.pem
+ KEY=/skf-flask/server.key
+ PORT=443
+ [[ UlyPmpz0LCXiJbSm3kFKOqNhLsG8v-zyQ-baTQP_OCaevu0cEUE_QjrWZ9O6dkikKFIdg7ojc8gKOx2ZVMhATA != \c\h\a\n\g\e\m\e ]]
+ perl -pi -e 's/JWT_SECRET = '\'''\''/JWT_SECRET = '\''UlyPmpz0LCXiJbSm3kFKOqNhLsG8v-zyQ-baTQP_OCaevu0cEUE_QjrWZ9O6dkikKFIdg7ojc8gKOx2ZVMhATA'\''/' /skf-flask/skf/settings.py
+ [[ localhost != '' ]]
+ perl -pi -e 's/\*/https:\/\/localhost/' /skf-flask/skf/settings.py
+ perl -pi -e 's/http:\/\/127.0.0.1:8888\/api/https:\/\/localhost\/api/' /skf-flask/Angular/src/environments/environment.prod.ts
+ mkdir /run/nginx
+ nginx
**nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)**
+ sleep 5
+ rm /etc/nginx/conf.d/default.conf
+ killall nginx
killall: nginx: no process killed
+ [[ true == \t\r\u\e ]]
+ cp /skf-flask/Docker/alpine/site-tls.conf /etc/nginx/conf.d/default.conf
+ sleep 5
+ nginx
**nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)**
+ /wrapper.sh
+ ORIGIN=localhost
+ cd /skf-flask/Angular
+ ng serve --configuration=production --host 0.0.0.0 --publicHost localhost

It seems the protocol is ipv6 for the nginx in the docker image, my system supports only ipv4, can you provide another docker image with ipv4 instead, or correct the current image ?

thanks a lot

**Comment by blabla1337** [comment]
Hi @ferrandpaul,

Aaah I see, its related to the fact that there is no IPv6 available and thus is fails indeed.
I will remove the below 2 lines from the config file of Nginx so it will only be available on IPv4

    listen [::]:80 default_server;
    listen [::]:443 ssl;

I will release soon a new build to have this fixed.

Kind regards,
Glenn
