### ISSUE TITLE
Please enable the filters for coding language on "Code Examples" page

### ISSUE THREAD

**Issue by ravi-mrk** [blabla1337/skf-flask#557]
The Coding Language filters were enabled earlier and were very helpful to easily get to the relevant issue in a filtered language(Java/Python/PhP, etc.). After these filters are removed in latest versions of SKF, it is becoming difficult to identify or list down all the vulnerabilities in a specific coding language as the user has to scroll through the length of the "Code Examples" page.

**Comment by mzfr** [comment]
I looked at the git history of the project, but couldn't find how this was implemented before.

If I were to implement it from scratch, I'd add an `ng-select` right next to the search input box (of all languages) and allow user to filter examples of only the selected language.

**Comment by mzfr** [comment]
An easy way to do it would be to just have one search box which filters both the title and the language of the example. So you can just type in `asp` in the search box itself.
