### ISSUE TITLE
Provide a configurable default page option

### ISSUE THREAD

**Issue by dmspils** [blabla1337/skf-flask#567]
The app currently defaults to /login.
I don't need the majority of my users to log in as the app is sat behind client cert auth and asking them to hit `skip` detracts from the UX.
Personally, I would like /dashboard to be the default page but a configurable option, via K8s yaml, would be ideal.

**Comment by blabla1337** [comment]
Hi Dan,

Check we will look into it, small question you guys are also planning to use the project flow of selecting requirements? Because normally for that part you need to be authenticated and also to make updates on KB or Code items for example. Do you want to only change the landing page URL or also want to remove the authentication part as well?

**Comment by dmspils** [comment]
Sorry, I missed this comment, need to check my GitHub notifications!

We aren't using the requirements/checklists. That may come at a later date if we get reaction with SKF.

I only want the landing page to be configurable as having auth is something we need for making changes. But it would be nicer if the user only ends up on an auth page when they try to perform an action that requires auth, as opposed to it being in their faces every time they hit the app.

**Comment by dmspils** [comment]
G'day - in follow up to this issue, is there any manual workaround that I can bodge in as a short term fix as the login page causes a lot of confusion (and some resistance - it's seen as a barrier to entry) to using the knowledge base?

**Comment by blabla1337** [comment]
Hi dan,

Actually we are almost ready to release a new major version of skf. One of
the improvements we have implemented is the disable login option, this will
be default load skf dashboard page. We are planning to release the new
version soon :)

**Comment by blabla1337** [comment]
We have added this but needs some testing, will release the update soon

**Comment by blabla1337** [comment]
Done see SOO branch, by default it will have no login page anymore only if you use the KeyCloak and Kraken setup
