### ISSUE TITLE
Angular Compiling Errors

### ISSUE THREAD

**Issue by enderax-letgo** [blabla1337/skf-flask#588]
Hello!

I really liked this project. Thanks for all your effort. I want to install it on EC2 to use internally.

But I am getting errors while installing it locally by following this https://github.com/blabla1337/skf-flask/tree/master/installations/local

Angular CLI: 9.1.7
Node: 12.18.0
OS: Ubuntu 16.04
Angular: 9.1.9

When I run the following command:

`cd /tmp/skf-flask/Angular; ng build --aot --configuration=production`

I got the following errors:

> 0% compiling
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/http : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling ngx-markdown : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling angular2-highlight-js : main as commonjs
Compiling @ng-select/ng-select : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
ERROR in app/knowledgebase/knowledgebase.component.html:36:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'KnowledgebaseComponent'.
36                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/knowledgebase/knowledgebase.component.ts:11:16
    11   templateUrl: './knowledgebase.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component KnowledgebaseComponent.
app/knowledgebase/knowledgebase.component.html:36:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'KnowledgebaseComponent'.
36                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/knowledgebase/knowledgebase.component.ts:11:16
    11   templateUrl: './knowledgebase.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component KnowledgebaseComponent.
app/code-examples/code-examples.component.html:37:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'CodeExamplesComponent'.
37                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/code-examples/code-examples.component.ts:15:16
    15   templateUrl: './code-examples.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component CodeExamplesComponent.
app/code-examples/code-examples.component.html:37:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'CodeExamplesComponent'.
37                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/code-examples/code-examples.component.ts:15:16
    15   templateUrl: './code-examples.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component CodeExamplesComponent.
app/checklist/checklist.component.html:42:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'ChecklistComponent'.
42                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/checklist/checklist.component.ts:12:16
    12   templateUrl: './checklist.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChecklistComponent.
app/checklist/checklist.component.html:42:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'ChecklistComponent'.
42                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/checklist/checklist.component.ts:12:16
    12   templateUrl: './checklist.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChecklistComponent.
app/checklist-summary/checklist-summary.component.html:40:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'ChecklistSummaryComponent'.
40                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/checklist-summary/checklist-summary.component.ts:12:16
    12   templateUrl: './checklist-summary.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChecklistSummaryComponent.
app/checklist-summary/checklist-summary.component.html:40:31 - error TS2339: Property 'selectUndefinedOptionValue' does not exist on type 'ChecklistSummaryComponent'.
40                      <option selected [value]="selectUndefinedOptionValue">Select a category to work with!</option>
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  app/checklist-summary/checklist-summary.component.ts:12:16
    12   templateUrl: './checklist-summary.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ChecklistSummaryComponent.

**Comment by WANGQINWU** [comment]
I got the same issue too.
One simple solution, you can delete <option selected [value]="selectUndefinedOptionValue"> this line in html file to solve problem. Doing this, it will miss a fix tip in selects.
sed -i "/selectUndefinedOptionValue/d" checklist-summary.component.html
Or, you can fix the problem in ts file to create a variable.

**Comment by enderax-letgo** [comment]
@WANGQINWU Thank you.

I added 
`public selectUndefinedOptionValue:any;`
to each ts file gives the error and it worked. 

For those have same error. ts file looks like this after the change:

```
...
@Component({
  selector: 'app-knowledgebase',
  templateUrl: './knowledgebase.component.html',
  providers: [KnowledgebaseService, CategoryService]
})

export class KnowledgebaseComponent implements OnInit
{
  knowledgebaseForm: FormGroup;
  public isSubmitted: boolean;
  public delete: string;
  public knowledgeitems: Knowledgebase[] = [];
  public queryString: string;
  public categories: Category[];
  public category_id: number;
  public selectUndefinedOptionValue:any;

  get formControls() { return this.knowledgebaseForm.controls; }
...
```

**Comment by blabla1337** [comment]
I guys,

Thanks for helping each other, i had a fix for it in dev branch and also pushed this fix to the master branch.

Kind regards,
Glenn
