### ISSUE TITLE
Code examples view

### ISSUE THREAD

**Issue by RiieCco** [blabla1337/skf-flask#601]
Currently we have a view for code examples that display the code examples that are available by means of a accordeon. In theory there is nothing really wrong with this approach. However, we could do something with the styling.

Acceptance criteria for code example view:

- Users are able to search for a specific code example by name
- Users are able to apply labels to filter out code examples by programming language
- Administrators are able to add new code examples
- Administrators are able to delete existing code examples
- Administrators are able to edit code examples

# Current state:

## Main view

<img width="1662" alt="Schermafbeelding 2020-06-11 om 16 25 31" src="https://user-images.githubusercontent.com/8506705/84398510-54266000-ac00-11ea-9c78-cc2d938eb266.png">

## Main view accordeon extended

<img width="1663" alt="Schermafbeelding 2020-06-11 om 16 29 12" src="https://user-images.githubusercontent.com/8506705/84399669-68b72800-ac01-11ea-8a35-51cf83ac0c0b.png">

## View with filters

<img width="1668" alt="Schermafbeelding 2020-06-11 om 16 29 41" src="https://user-images.githubusercontent.com/8506705/84399559-4ae9c300-ac01-11ea-98af-e9bb79e1fe98.png">

## Update code example

<img width="1666" alt="Schermafbeelding 2020-06-11 om 16 29 23" src="https://user-images.githubusercontent.com/8506705/84399830-9ac88a00-ac01-11ea-9108-e4d938dc5f9e.png">

<img width="1666" alt="Schermafbeelding 2020-06-11 om 16 29 23" src="https://user-images.githubusercontent.com/8506705/84400582-833dd100-ac02-11ea-8c1d-22021e44d2c9.png">
# Add code example

<img width="1660" alt="Schermafbeelding 2020-06-11 om 16 28 58" src="https://user-images.githubusercontent.com/8506705/84399738-7e2c5200-ac01-11ea-8b22-cccfe1b63f4e.png">

## Delete code example

<img width="1655" alt="Schermafbeelding 2020-06-11 om 16 29 52" src="https://user-images.githubusercontent.com/8506705/84399583-50dfa400-ac01-11ea-88fe-6e2b1149c8ec.png">

## Update code example

<img width="1666" alt="Schermafbeelding 2020-06-11 om 16 29 23" src="https://user-images.githubusercontent.com/8506705/84400617-8c2ea280-ac02-11ea-9f74-ace0295da836.png">

**Comment by AkashM398** [comment]
Started Working on this..
Date - 13 - 06 - 2020
