### ISSUE TITLE
Unable to upload content - PUT method 500 server error.

### ISSUE THREAD

**Issue by CarlesLlobet** [blabla1337/skf-flask#632]
Hi @blabla1337,

After helping us (@mozo95 and me) with a workaround to our [URL-change issue](https://github.com/blabla1337/skf-flask/issues/614), we have been able to deploy our solution to Azure.
In order to do that with the workaround you suggested, we have had to create an image with the url substitution and upload it to our own docker registry, to afterwards generate the Azure Web App container from that "fixed" image.

Now we can indeed perform our First Run, and we have persistant access with our admin user (as the DB is in a volume).

The problem is that whenever we try to upload any content, we get an internal 500 error message. We've thought about Azure not allowing PUT by default, but we haven't found anything on your ["Deploy to Azure"](https://github.com/blabla1337/skf-flask/tree/master/installations/azure-deployment) documentation.

Here you can see how we create a Code Example and the api returns a 500 server error in firebug:
![image](https://user-images.githubusercontent.com/6575422/87286130-bf619b80-c4f8-11ea-9917-ad2be333bbe3.png)

**Comment by CarlesLlobet** [comment]
We have seen in the Azure logs that the log states the db is readonly:
![image](https://user-images.githubusercontent.com/6575422/87291445-9f81a600-c4ff-11ea-9228-a6d891e7b3eb.png)

But we have also seen the permissions on [Azure documentation](https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-serve-content-from-azure-storage) states that in Azure Storage with App Service supports mounting Azure Files containers (Read / Write) and **Azure Blob containers (Read Only)**

**Comment by blabla1337** [comment]
@CarlesLlobet Aah yes we had that issue indeed and the fix you did is actually a really good one, its a more solid approach then the one I mentioned by replacing it in the Docker container as its a dirty fix...

Hmm about the issue of the DB, what you could do is instead using the sqlite database you can also configure a mysql database with the env variable SKF_DB_URL:
https://github.com/blabla1337/skf-flask/blob/master/skf/settings.py#L21

for example:
export SKF_DB_URL= 'mysql+pymysql://root:H5hng15K@localhost/skf?charset=utf8mb4'

If you wish to use this then you must create a mysql server and already create a database skf
when you then boot the API it should create all the tables and content in this Mysql db


Remark:
Also we are currently really busy with a ton of improvements and are planning a major release of SKF in around 6 weeks.
We have created separate containers for the API and Angular to make the whole deployment easier and also to work better in Kubernetes. I would also suggest to have a look at the dev branch and see if you can also set this up:

https://github.com/blabla1337/skf-flask/tree/dev/Docker/alpine-cloud/k8s
