### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by ghost** [blabla1337/skf-flask#661]
There's a small but extremely necessary things they are:

- When you forgot your password, users can recover it without the necessity to touch the database
- Users can create their own check list, but cannot touch the checklists of the others, actual privileges need to be 1;2;3;4 to handle this, an that users can create other users, authorize them and so on.
- SKF should have the ability to delete users

**Comment by insidesecurity-ianfleming** [comment]
@telekomancer

**Comment by blabla1337** [comment]
All done on Keycloak and Kraken level
