### ISSUE TITLE
Session hijacking has to check on 'concurrent sessions' (code example)

### ISSUE THREAD

**Issue by RiieCco** [blabla1337/skf-flask#67]

**Comment by jowasp** [comment]
Session hijacking must also check  concurrent sessions (provide example)
[Translation]
This is exam plain in the ASVS:
3.16
Verify that the application limits the number of active concurrent sessions.

**Comment by jmanico** [comment]
Bah, limiting multiple concurrent sessions doesn't always make sense. You may want to log into the web, your mobile and your iPad together in some cases. This is not a hard rule, just a suggestion.

More importantly, inform users of open sessions and give them a chance to close them, like we see at google and other services.

--
Jim Manico
@Manicode

**Comment by jowasp** [comment]
Agree with @jmanico I was just translating ;-P
