### ISSUE TITLE
wrapper.sh issues errors

### ISSUE THREAD

**Issue by ip6li** [blabla1337/skf-flask#679]
wrapper.sh issues errors due to a type mismatch between PROCESS_[12]_STATUS and expected type for comparison. See attachment for fix.

[wrapper.patch.txt](https://github.com/blabla1337/skf-flask/files/5049936/wrapper.patch.txt)

**Comment by blabla1337** [comment]
Thanks for bringing this to our attention, with the new release we just did this is not an issue anymore :)
