### ISSUE TITLE
Deleting function shows "Delete project" button

### ISSUE THREAD

**Issue by Mafti** [blabla1337/skf-flask#69]
When deleting a function the button is labeled "Delete project"
Bit scary.

It does delete the function and not the project.

**Comment by RiieCco** [comment]
Oh thanx haha that sounds like a typo, wil be taken into account for the
next release.

Thank you very much for submitting! :-)
Op 24 nov. 2015 8:29 PM schreef "Mafti" <notifications@github.com>:

**Comment by blabla1337** [comment]
Fixed in last release
