### ISSUE TITLE
Search on https://skf.readme.io/docs/code-examples doesn't seem to be working

### ISSUE THREAD

**Issue by DinisCruz** [blabla1337/skf-flask#70]
I would expect to be able to search (for something like XSS) here:

![image](https://cloud.githubusercontent.com/assets/656739/11613440/85ab05ec-9c18-11e5-9179-6df1e42e7b0d.png)

**Comment by blabla1337** [comment]
Hi DenisCrus,

This service "skf.readme.io" is the documentation page we use on how ti install the SKF project and how you can use it. If you want to have a look at the actual SKF framework we have an online version thats being pulled every hour from our github. You can login and check it out here:

http://demo.securityknowledgeframework.org

Username: admin
Password: test-skf

Greetz,
Glenn
