### ISSUE TITLE
What is the default login (userid/password)?

### ISSUE THREAD

**Issue by NetEyes** [blabla1337/skf-flask#718]
Greetings,
After installing docker image on Ubuntu 16, i can view the login page.
What is the default login (userid/password)?

**Comment by Scopestyle** [comment]
Hi @NetEyes, you need to do a first login procedure as described here: https://skf.readme.io/docs/first-run

**Comment by ducna96** [comment]
> Hi @NetEyes, you need to do a first login procedure as described here: https://skf.readme.io/docs/first-run

i just follow your docs, but i still can't login, what do i wrong step?
![image](https://user-images.githubusercontent.com/35019158/166618317-7c1b6acd-e5f1-4cee-b7c1-2ab681134877.png)

![image](https://user-images.githubusercontent.com/35019158/166618248-aa6c6c0c-3b2c-484d-b86b-128ebae016ce.png)

**Comment by shahamit** [comment]
I am facing the same issue. I can't login even after registering to the locally installed SKF application using docker-compose. What is the issue?

**Comment by cptfixit** [comment]
You are probably running into this issue -> https://github.com/blabla1337/skf-flask/issues/831

Please close this issue; the OP is long gone.
