### ISSUE TITLE
SKF_Login option removal

### ISSUE THREAD

**Issue by telekomancer** [blabla1337/skf-flask#727]
I guess that could be a very good option, to remove the "Skip Login" button in case that the SKF could be exposed to the internet do a different reasons related to infrastructure or networking desitions. So i guess that could exist and option on environment parameters that could allow that, for example:

```
environment:
...
- SKIP_LOGIN: "False"
...
```

So that could give you the option to avoid or skip login, button itself isn't so important, i see that button calls the API on URL: `http://localhost/api/user/skip`that, generate an Authorization Token, so the option on environment, probably should delete the authorization token or something like that.

With the `False` or `True` Flags i mean that:

- False: Should not allow you to skip the login, so must be a valid and registered user, with
- True: This should allow to skip the login and visit the SKF as anonymous user.

**Comment by blabla1337** [comment]
5. By default, the login will be skipped when using docker compose locally. To change this, update
    the value of `SKIP_LOGIN` to `skfprovider` in `docker-compose.yml`.

**Comment by blabla1337** [comment]
Implemented, closing ticket
