### ISSUE TITLE
Frontend bug with multiple Compliance Evidence tabs open in sprint result

### ISSUE THREAD

**Issue by plouffer** [blabla1337/skf-flask#730]
I experience a frontend bug: 
In a sprint result it is not possible to leave multiple Compliance Evidence text boxes open of different checks. As soon as I open the compliance tab of another check, while leaving yet another one open, the text in all boxes is replaced with the last opened compliance evidence text.

For example, see the following two screenshots.
When a first Compliance Evidence textbox is open:

![image](https://user-images.githubusercontent.com/74661249/103539724-d6c28580-4e98-11eb-8b5d-27ef2246a9b9.png)

When a second Compliance Evidence tab is opened on the same Sprint result page:

![image](https://user-images.githubusercontent.com/74661249/103540643-556bf280-4e9a-11eb-92d3-15a7751e9901.png)

Thanks in advance for checking this!

**Comment by RiieCco** [comment]
front-end gets a major overhaul so these pages will also be re-designed.
