### ISSUE TITLE
Getting 404 when visiting https://beta.securityknowledgeframework.org/

### ISSUE THREAD

**Issue by paoga87** [blabla1337/skf-flask#732]
Looks like there are some certificate issues with the demo page, and once you get to it, it returns a 404 error.

**Comment by plouffer** [comment]
I see here https://securityknowledgeframework.org/demo.php the demo site is at https://demo.securityknowledgeframework.org

**Comment by RiieCco** [comment]
Hey,

That is correct we use the beta domain for testing purposes now ^^

The "demo" is the correct one to use 👌 😀

**Comment by paoga87** [comment]
Thank you for clarifying, @RiieCco. I've sent in a PR to update the URL on owasp.org.
