### ISSUE TITLE
Cannot generate requirements (demo site & local docker instance)

### ISSUE THREAD

**Issue by JohanDi** [blabla1337/skf-flask#733]
There seems to be a problem on the demo site. I cannot generate a requirements sprint. The PUT request to /api/questions/store produces a 400 response.

![image](https://user-images.githubusercontent.com/6392042/105993565-7b9e4000-609e-11eb-8518-c101ced0c9e7.png)

![image](https://user-images.githubusercontent.com/6392042/105992967-a9cf5000-609d-11eb-9660-5c19951011b4.png)

The same problem manifests itself on a local instance of the application installed with Docker.

**Comment by blabla1337** [comment]
Hi Johan,

Thanks for letting me know, just for my information: what checklist did you
selected?

Kind regards
Glenn

**Comment by JohanDi** [comment]
Checklist: Web Application
Maturity level 2
I have trued to select multiple categories, have tried with creating a new feature or existing and they all run into the same error

**Comment by blabla1337** [comment]
Thanks and maybe one more question you also had this with the same web
checklist on the other maturlevels or only the level 2?

Well anyways we will look into it and get back to you.

Thanks

**Comment by JohanDi** [comment]
I wanted to let you know that I now managed to generate requirements on the demo site. I do not know whether you implemented any changes there. But I wanted to let you know that I now managed to generate requirements. But only after force fetching the cache from the server.

**Comment by blabla1337** [comment]
I think it is the same issue as this one:
https://github.com/blabla1337/skf-flask/issues/735

Will test the fix and let you all know

**Comment by blabla1337** [comment]
Fixed
