### ISSUE TITLE
Creating requirements hangs when answering no to all questionnaire question 

### ISSUE THREAD

**Issue by Superpiojo17** [blabla1337/skf-flask#735]
If you go through the process of creating a new set of requirements, and you answer no to all the questions in the questionnaire, the tool hangs. Additionally, it seems that the requirement functionality does not working correctly after you run into this bug. I have tracked down the part of the code that causes this and have provided a screenshots. The code file is https://github.com/blabla1337/skf-flask/blob/main/skf/api/questions/business.py
specifically line 36. As you can see from my print statements, if you answer no to all of the questions, Data is empty. Therefore you never enter the for loop and never set project id. So when you get down to line 40, you are trying to pass in project_id, but it has not been defined (since you never went into the for loop b/c data is empty). I hope my screenshots explain the situation well enough. 
<img width="627" alt="bugCode" src="https://user-images.githubusercontent.com/21108523/108742915-e2781300-74fd-11eb-8a66-efd48ffd5d7a.PNG">

<img width="400" alt="error" src="https://user-images.githubusercontent.com/21108523/108742936-e73cc700-74fd-11eb-9052-22574cd4ce96.PNG">

<img width="69" alt="printStatement" src="https://user-images.githubusercontent.com/21108523/108745866-3f28fd00-7501-11eb-826c-986281ef5348.PNG">

<img width="915" alt="frontEndError2" src="https://user-images.githubusercontent.com/21108523/108742958-eb68e480-74fd-11eb-96ec-ad456beea6a8.PNG">

**Comment by Superpiojo17** [comment]
Upon more digging, I think the real issue lies in 
https://github.com/blabla1337/skf-flask/blob/main/Angular2/src/app/pages/projects/wizard/wizard.component.ts
on line 141. It only checks if count_sprint == 0, but it should check
if count_sprint == 0 || this.sprintStore.length == 0

as well, or at least that is what I believe.

**Comment by blabla1337** [comment]
Thank you for the impressive debugging, we really appreciate it!
I will give it a try locally and see if it resolved the issue

**Comment by blabla1337** [comment]
@Superpiojo17 Thank you for the suggested fix and we had implemented it a while ago already but the ticket was still open :)
