### ISSUE TITLE
File upload option in checklist items 

### ISSUE THREAD

**Issue by seenu0991** [blabla1337/skf-flask#739]
Hello, 

From security audit perspective, It's good to have a File upload option in evidence column in the checklist. It would be helpful to communicate the issues  to the stakeholder. I aware that ASVS is lift shift approach in SDLC but sometime it also helps to perform the review after the deployment process.

**Comment by blabla1337** [comment]
For now we will not implement this feature, most people use actually their own evidence system like Jira, Service Now or Defect Dojo and use those places to collect and store the requirements and evidences
