### ISSUE TITLE
Admin credentials for demo-site not working

### ISSUE THREAD

**Issue by RasmusWL** [blabla1337/skf-flask#740]
Trying to log into the [demo site](https://demo.securityknowledgeframework.org/auth/login) with `admin` / `test-skf` fails with _Username or Password is incorrect_. Only after trying that 4 times, did I realize that there was a `Skip Login` button.

If the intention is that you should use the `Skip Login` feature and not use admin credentials, I would recommend updating the landing page to reflect that :wink:

**Comment by 0x1F602** [comment]
Can confirm. I suspect the site's compromised (ironically)

**Comment by blabla1337** [comment]
Hi all,

Thanks for letting us know, will restore it in the upcoming days.
Sometimes we see that "a user" disabled the admin account so that one is not accessible anymore.

Yes the Skip Login will always work but some functionality is not visible then.

Kind regards,
Glenn
