### ISSUE TITLE
platform attribute error  lines in the docker-compose.yml

### ISSUE THREAD

**Issue by blabla1337** [blabla1337/skf-flask#744]
in Ubuntu you need to install docker-compose manually (apt install docker-compose). I also found that the linux Version of docker-compose does not support the "platform" attribute in the docker-compose.yml file. Obviously the platform attribute was introduced in the past (v2.4) but with a newer version of docker (v3.5 and later) was removed again (found indicators for this here: docker/cli#1050).

Todo:

remove platform attributes docker-compose.yml file

**Comment by convenient** [comment]
@blabla1337 just commenting as i saw this linked just after i was active on https://github.com/docker/cli/issues/1050.

FYI If you remove the platform info this may not work on apple silicon chipset as they need definitions there
