### ISSUE TITLE
Can't activate admin account

### ISSUE THREAD

**Issue by rstmm** [blabla1337/skf-flask#745]
I am currently trying out the application. I set it up via Docker as in the install guide (https://github.com/blabla1337/skf-flask/tree/main/installations/docker). 
I skipped the Kubernetes activation as I don't want to test the lab features at the moment. I think this should not have an impact on my issue though.

I can open localhost and see the (what I think is a) Demo version of the application, missing buttons for creating projects etc. It automatically skips the login immediately. I found the documentation for activating the admin account (https://skf.readme.io/docs/first-run), but the login is only shown for half a second. I was able to stop the redirect by Escape key, then click the Activate link. I entered the data from the setup guide and saved it. But I still don't get to the login. If I click logout, it automatically redirects from login page again back to the demo application.

Did I miss a step here?

**Comment by JOT85** [comment]
Added to the docs in #753!

**Comment by blabla1337** [comment]
Thanks for the help and fixing this issue
