### ISSUE TITLE
Limiting the number of labs 

### ISSUE THREAD

**Issue by shahamit** [blabla1337/skf-flask#759]
We plan to deploy SKF locally and share it within our organisation for developers to adopt secure development lifecyle. The labs feature looks great in terms of understanding security vulnerabilities. Since the SKF application would be shared with few hundreds of developers and testers, how can we restrict the number of labs that get started on the application? 
For e.g. we would want to restrict max 10 labs to be started in total so that the server is not overloaded with unlimited number of docker instances that could get spawned each time a developer starts a lab. Can this be configured?

On a related note can labs as a feature be hidden?

Thanks.

**Comment by RiieCco** [comment]
I assume the max deployment of labs can be configured in Kubernetes?

The labs as a feature can be hidden by toggling the KUBERNETES_ENABLED flag in the angular environments.ts:

```
/skf-flask/Angular2/src/environments


  /* 
     This config is about wether to show the SKF lab deployment options,  
     True || False -> This affects the way the lab page is shown with deployment buttons
  */
  KUBERNETES_ENABLED: 'False',
  
```
