### ISSUE TITLE
Repetition of Security Checks in Projects ASVS L1 - Authentication Verification Requirements

### ISSUE THREAD

**Issue by deFr0ggy** [blabla1337/skf-flask#760]
I was navigating through the application and found that there is a repetition of each check in Projects -> ASVS L1 -> Authentication Verification Requirements

Not sure if this is by design or an error. Though both entries consist of same details!

https://demo.securityknowledgeframework.org/projects/summary/

<img width="1534" alt="Screenshot 2022-01-31 at 9 38 53 PM" src="https://user-images.githubusercontent.com/16836050/151834827-29847e39-fbd6-467f-8a28-5721b3e67fc8.png">

Thank You!

**Comment by blabla1337** [comment]
I think this was a one off error, please reopen if comes back
