### ISSUE TITLE
ubuntu install 

### ISSUE THREAD

**Issue by javabeanz** [blabla1337/skf-flask#78]
hi guys, I get SSL_ERROR_WEAK_SERVER_CERT_KEY when running 0.2.8 on Ubuntu and opening the root page in firefox. Nothing serious, just a heads up. Great work !

**Comment by blabla1337** [comment]
Hi Javabeanz,

Thanks for the feedback, we are planning to remove the SSL/TLS stuff from the project and let people set it up correctly in their webserver config.

Greetz,
Glenn
