### ISSUE TITLE
Getting 502 during user activation.

### ISSUE THREAD

**Issue by spmishra121** [blabla1337/skf-flask#802]
I had installed SKF at my server. I am connected my server using VPN.

I had followed following installation process...
1. Clone the skf repository at my local directory.
2. Changes docker-compose as per our suitability like...

 # Run docker-compose up

version: '2'
services:
  rabbitmq:
    container_name: skf-rabbitmq_container
    image: rabbitmq:3.8.19
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin-skf-secret
    ports:
        - "5672:5672"
        - "15672:15672"

  mysql:
    container_name: skf-mysql_container
    image: blabla1337/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'skf'
      MYSQL_ROOT_PASSWORD: 'admin-skf-secret'
      MYSQL_DEFAULT_PASS: 'admin-skf-secret'
      MYSQL_DEFAULT_USER: 'root'
    ports:
      - '3306:3306'
    volumes:
       - mysql_data:/var/lib/mysql

  nginx:
    container_name: skf-nginx_container
    restart: always
    image: nginx
    volumes:
      - ./Docker/compose/site.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  skf-angular:
    container_name: skf-angular_container
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    image: "blabla1337/skf-angular:4.0.2"
    environment:
      **- FRONTEND_URI=http://XX.XX.XX.XXX**

  skf-api:
    container_name: skf-api_container
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    volumes:
      - ~/.kube/config:/home/user_api/.kube/config
    image: "blabla1337/skf-api:4.0.4"
    environment:
      - SKF_FLASK_DEBUG=False
      **- SKF_API_URL=http://XX.XX.XX.XXX:8888/api**
      - SKF_TESTING=False
      - SKF_DB_URL=mysql+pymysql://root:admin-skf-secret@mysql/skf?charset=utf8mb4
      - SKF_JWT_SECRET=please_change_this_value_to_be_random
      - SKF_LABS_DOMAIN=http://10.25.51.247
      - SKF_LABS_DEPLOY_MODE=port
      - RABBIT_MQ_CONN_STRING=rabbitmq
      - LABS_KUBE_CONF=YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljY_update_me...
      #- LABS_KUBE_CONF=base64_string_here_of_the_content_of_the .kube/config file_for_example: cat ~/.kube/config | base64
      #- GOOGLE_CREDENTIALS=base64_string_here_of_the_content_of_the gsa-key.json file_for_example: cat gsa-key.json | base64
      #- SKF_LABS_DEPLOY_MODE=subdomain
      #- JWT_ENABLED="False"
      #- SKF_DOJO_API_KEY=
volumes:
  mysql_data: {}

Note: Highlighted the changed part.
3. Skipped step 3 from "Docker-compose local how to" guidelines. I think this is no use
4. Run docker compose file.
5. But I am getting below error in log...
![image](https://user-images.githubusercontent.com/6615148/182810324-cbd5d205-5d5c-4122-a639-154678b2f7ab.png)

When I am analysing further, I have found that docker container run this container with user owner and group user_api. See screenshot...
![image](https://user-images.githubusercontent.com/6615148/182811495-d4f29bb1-0667-4ed1-947d-9b7739503023.png)
 

When I am browsing IP address, front page is opening and when I am clicking on account activation link. I am getting 405...

Please let me know, If anything I am missing?

**Comment by RiieCco** [comment]
Hey @spmishra121,

>When I am browsing IP address, front page is opening and when I am clicking on account activation link. I am getting 405...

Can you maybe show me the request/response from the "developer tools" network tab? :-)

**Comment by spmishra121** [comment]
Thank @RiieCco , I have modified the configuration, highlighted in bold above and use default config as provided with source code. Now I am getting 502. Request and Response is below:
![image](https://user-images.githubusercontent.com/6615148/182823726-12b8b9fc-b8ce-493a-b393-0251cbe5014e.png)


Request and Response header:
![image](https://user-images.githubusercontent.com/6615148/182823919-93cdf28a-7713-46ce-bf8d-becf36e25ab3.png)


Request Payload:
![image](https://user-images.githubusercontent.com/6615148/182824059-691e8fde-e072-4b41-aec4-4beb9d82337b.png)

Response:
![image](https://user-images.githubusercontent.com/6615148/182824169-7e331fed-5576-46d4-a85e-74c892753777.png)

**Comment by spmishra121** [comment]
Hi @RiieCco , Any update on this ticket?

**Comment by spmishra121** [comment]
Solved

**Comment by cptfixit** [comment]
> "_Solved_"

Without trying to be mean, this is the most useless way of closing a reported issue. 

How did you resolve the issue? What was the problem and what was the solution?
