### ISSUE TITLE
TravisCI doesn't seem to be up & running

### ISSUE THREAD

**Issue by toubou91** [blabla1337/skf-flask#84]
Hey,

well done for the project.

The [link](https://travis-ci.org/blabla1337/skf-flask) for Travis seem to be inconsistent for this time of being:

![image](https://cloud.githubusercontent.com/assets/5684688/15251718/fdb12884-192a-11e6-9dde-23768a1c49c5.png)

**Comment by blabla1337** [comment]
Hi Toubou91,

Thanks, maybe there was a hick-up somewhere. For me it worked all the time.

Greetz,
Glenn
