### ISSUE TITLE
End-user should be explicitly informed of the admin user's credentials

### ISSUE THREAD

**Issue by toubou91** [blabla1337/skf-flask#86]
Currently, it is not clear to the end-user what the credentials for the `admin` account are, even if one consults the [first run](https://skf.readme.io/docs/first-run) page.

**Comment by blabla1337** [comment]
That is true, in the beginning there is no credentials for the admin account. You can only create it by following the [first run](https://skf.readme.io/docs/first-run) page.

**Comment by toubou91** [comment]
I actually meant that from my point of view, it wasn't clear, even when I consulted the first run page. I'm not familiar with tokens, authentications and stuff, I just wanted to setup the application locally in order to have it up and running and I found this part a bit confusing.

Again, this is my opinion, but other people might be in the same situation, having not so much security/authorization knowledge.

Cheers!

**Comment by RiieCco** [comment]
Hey Thodoris,

Ah okee i see, sorry for misunderstanding you!
As we speak we are rebuilding the SKF to an API so we would love to take
your feedback into consideration while designing.

Cheers!

2016-05-26 11:37 GMT+02:00 Thodoris Bais <notifications@github.com>:

**Comment by toubou91** [comment]
Heeey @RiieCco ,

no prob, but this raises another issue, I guess, for the people who are about to contribute to existing issues.

For example, let's say that I wanna contribute by providing some Java examples, but I am not aware that the main version of the project will actually be changed to the API one, so, I will then have to either provide the implementation again or what?

* Maybe I don't know how you're thinking about the branching/tagging.

Cheers!
