### ISSUE TITLE
Discussion around the rebuild

### ISSUE THREAD

**Issue by Luminger** [blabla1337/skf-flask#93]
I wanted to create a quick rundown of projects I would personally use to get the rewrite done with (as I've worked with some of those already) and I think it's worth having the potential stack discussed before it actually gets implemented. While the frontend will be done with Angular, on the server side it's just clear that it will now be an API and probably done with flask.
# A new ORM stack

While sqlite and plain SQL queries are nice for the time being, I believe the rewrite should use a more sophisticated way of talking to the database of choice - people would probably like to run a 'real database' which they can replicate and backup as they are used to.
- [SQLAlchemy](http://www.sqlalchemy.org/) - To allow people to use any database backend they want (to a certain extend) it's probably a good idea to move a way from plain sqlite3 queries to an actual ORM. 
- [Alembic](http://alembic.zzzcomputing.com/en/latest/) - Alembic gives you migrations for SQLAlchemy. I've worked with it a couple of times and it was certainly a good addition to the whole mix. As databases change from time to time, it's probably wise to provide some migrations for users.
- [flask-migrate](https://flask-migrate.readthedocs.io/en/latest/) - While I've never used it, it seems to be a nice addition to apply your migrations. Might we worth looking at.
# API Description projects

As the project will be API based in the futures, it's only reasonable to use some kind of API framework as it gets you all kind of neat benefits like automated client code generation, automated and interactive documentation etc.
- [Swagger](http://swagger.io/) - Probably the most well known API description project. I've used it before and I'm not sure if I would give it a shot again due to some pitfalls here and there (afair it was about the documentation generation part being not that easy as I thought it would be). Still, people love it and it's probably not the wrong choice to go with it.
- [api blueprint](https://apiblueprint.org/) - The project I would probably use next (never worked with it, but it looks more promising to me than Swagger right now). Main reason I consider it right now as my personal next choice is all the goodness around it (there are so many cool companion projects around it).
# How to run skf-flask afterwards

Currently the skf is ran by just starting the main application file and it's probably the right time to make operations people happy as well. I would propose migrating over to the standard way of doing python deployments.
- [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/) - The defacto standard in the python world, I probably don't need to write anything about it.
- [nginx](https://nginx.org/) - nginx goes well with uwsgi, also the most used combination out there. This has also the benefit that the SSL stuff can now be handled by nginx rather than have the application bend to have some kind of SSL here and there. Also this will allow people to scale the application (if there's ever the need to).
- [docker](https://docs.docker.com) - While python people are used to create a virtualenv and just go with it, another nice way to develop stuff is with a docker container right now. It's worth considering this as it will also enable a nice way to distrubute the app, via docker-compose.
- [docker-compose](https://docs.docker.com/compose/) - This is nowdays probably one of the easiest ways to get an application stack up and running. Once there's a stable docker image, the project should provide a docker-compose file which enables people to just spin up a whole stack (maybe composed out of database, nginx and the application).

This is more or less just a braindump with my personal opinions which I do think would do good to the project. I would like to see some discussion around it as I'm definitely not an authority when it comes to 'the right way', but I think that's a good starting point.

**Comment by blabla1337** [comment]
New version of SKF has implemented a lot of the above things mentioned
