### ISSUE TITLE
Recommendation to improve the SKF support for pre development phase (Architecture Phase)

### ISSUE THREAD

**Issue by ravisha20** [blabla1337/skf-flask#94]
I propose to introduce 2 new phases called Architecure phase & Test phase besides the pre & Post development phase. This will help to the align with software development lifecycle phases & early from the development phases to work from the tool. It will also help the dev. teams to seperate the central security functions (Security layer) & development specific security functions which needs to be implemented by each & every developer. Please find the details in the attached file
![skf](https://cloud.githubusercontent.com/assets/20205927/16454047/5897c132-3e0f-11e6-846c-8b051e41f94f.png)

**Comment by RiieCco** [comment]
This looks totally awesome!
We Will deffinitly take this into consideration with the new design, thank
you very much for this new insight! 😁

Op woensdag 29 juni 2016 heeft ravisha20 <notifications@github.com> het
volgende geschreven:

**Comment by blabla1337** [comment]
Added the Architecture Phase, when the OWASP testing guide has a new release we also will add this to SKF as the Test Phase

**Comment by blabla1337** [comment]
We used this new approach in the current release, we only need to create the test information.
Will create a seperate ticket for that and close this one.
