### ISSUE TITLE
Support for SAML2

### ISSUE THREAD

**Issue by Luminger** [blabla1337/skf-flask#95]
Organizations tend to love at least SAML2 based authentication. It would be great if the rewrite would support SAML (and possibly other) authentication schemas which are common.

Reasoning behind this request is that most people either want or have to use a unified authentication layer, this change would definitely help getting SKF adopted in (large) organizations.

**Comment by harshant** [comment]
Hi @blabla1337 , I can work on this issue to integrate SAML2 / Oauth2 functionality.

**Comment by blabla1337** [comment]
@harshant that would be really cool if you want to pick this up. Please when you pick it up use the dev branch

**Comment by harshant** [comment]
I will be implementing Oauth2(google) first

**Comment by harshant** [comment]
just a quick follow up, I have understood the whole code base and will submit a PR soon for Google OAuth support

**Comment by harshant** [comment]
Hi,
I have integrated the google oauth with the client-side flow and here is the main commit https://github.com/harshant/skf-flask/commit/c8f8aaf55f86c245641c22569bd1745fbc157fe9 in my fork of skf.

![Screenshot from 2019-03-23 01-40-54](https://user-images.githubusercontent.com/18645807/54850563-72f3ba80-4d0d-11e9-91db-86cf4d5629c5.png)

The login screen looks like the above screenshot, I have upgraded the jquery from slim to full version
If it looks good then I can make a Pull Request

**Comment by blabla1337** [comment]
This looks awesome dude! Really cool stuff, one question can you also add a bit of documentation to the readme page? 

Also is it possible you can put your change in the dev branch and make a PR for this one? We will release the dev branch real soon so we can take this with the major release we are planning.

But wow nice work, we really appreciate this!

**Comment by blabla1337** [comment]
Btw also one more remark,  would it be possible to do the JS file you created in Angular typescript in that page? Because otherwise we get a mixture and that could lead to more complexity and also security vulnerabilities ;)

**Comment by harshant** [comment]
Hi @blabla1337 ,
I have initially tried with "angular-6-social-login" npm module but keep on getting errors, it simply does not work and also there is no official npm module available by google for oauth

In the current flow the google access_token and email with which the user signed in is sent to flask-API, the flask-API query the google api for email associated with this access_token if the email matches with the provided one we sign in the user. 

I have used implicit flow rather than authorization code flow because then we need to securely store gogole api secret-key,

I am still refining it a little bit and will submit a PR probably tomorrow

**Comment by harshant** [comment]
HI,
I have again tried with angular-6-social-login and it works,  changed my implementation

**Comment by blabla1337** [comment]
Hi Harshant, 

Oooh that is really awesome, nice work! 👍 
Let me know when your can make the PR to the dev branch will add it straight away ;)

Kind regards,
Glenn

**Comment by oxdef** [comment]
@harshant Do you plan to implement OpenId Connect support?

**Comment by blabla1337** [comment]
@oxdef we have prepared the new SKF with OpenID and soon we will release a how to of it.
Will close this one as we have a duplicate already for it :)

**Comment by oxdef** [comment]
@blabla1337 Great news! Waiting for the release :)
